### ISSUE TITLE
Problem: blocks with multiple txs may fail light client app hash check

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1069]
Error messages:

```
1) Staking
--
806 | should support staking, unbonding and withdrawing:
807 | Error: Error when synchronizing wallet: Verify error: state app hash don't match block header
808 | at Object.exports.asyncMiddleman (test/core/utils.ts:108:9)
809 | at process._tickCallback (internal/process/next_tick.js:68:7)
810 |  
811 | 2) Wallet Auto-sync
812 | can auto-sync unlocked wallets:
813 | Error: Error when synchronizing receiver wallet: Verify error: state app hash don't match block header
814 | at Object.exports.asyncMiddleman (test/core/utils.ts:108:9)
815 | at process._tickCallback (internal/process/next_tick.js:68:7)
816 |  
817 | 3) Wallet transaction
818 | Zero Fee
819 | can transfer funds between two wallets:
820 | Error: Error when synchronizing receiver wallet: Verify error: state app hash don't match block header
821 | at Object.exports.asyncMiddleman (test/core/utils.ts:108:9)
822 | at process._tickCallback (internal/process/next_tick.js:68:7)


```

**Comment by tomtau** [comment]
As per discussion on Slack, this seems to be caused by the block results extraction in client -- it can be reproduced if block has 2+ valid TXs, and the order of TxIds when sorted in a map is different from DeliverTx order
