### ISSUE TITLE
Problem: chain-abci crashed during testing

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1105]
```
[2020-02-19T07:29:05Z INFO  chain_abci::app] received beginblock request
[2020-02-19T07:29:05Z INFO  chain_abci::app::app_init::validator_state] Cleaning metadata of removed council nodes
[2020-02-19T07:29:05Z INFO  chain_abci::app::app_init::validator_state] Removing metadata of node: 0x695a7a8ecd3aaa37f049cd4705208905893959e5 (ea5716bbd09ed6e7115596449c5536f6559b869b)
[2020-02-19T07:29:05Z INFO  chain_abci::app::app_init::validator_state] Removed tendermint address mapping (ea5716bbd09ed6e7115596449c5536f6559b869b)
[2020-02-19T07:29:05Z INFO  chain_abci::app::app_init::validator_state] Cleaning metadata of removed council nodes finished
[2020-02-19T07:29:05Z ERROR chain_abci::app::app_init::validator_state] Validator in `last_commit_info` is cleaned up/non-existent: ea5716bbd09ed6e7115596449c5536f6559b869b
thread 'tokio-runtime-worker-0' panicked at 'no entry found for key', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: std::panicking::begin_panic
  13: std::panicking::begin_panic
  14: core::option::Option<T>::expect
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:348
  15: <alloc::collections::btree::map::BTreeMap<K,V> as core::ops::index::Index<&Q>>::index
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/collections/btree/map.rs:1949
  16: chain_abci::app::app_init::validator_state::ValidatorState::lookup_address
             at chain-abci/src/app/app_init/validator_state.rs:463
  17: chain_abci::app::<impl abci::Application for chain_abci::app::app_init::ChainNodeApp<T>>::begin_block
             at /Users/yihuang/src/chain/chain-abci/src/app/mod.rs:123
  18: abci::server::respond
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/abci-0.6.5/src/server.rs:81
  19: abci::server::serve::{{closure}}::{{closure}}
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/abci-0.6.5/src/server.rs:38
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/ops/function.rs:285
  21: core::option::Option<T>::map
  22: <futures::stream::map::Map<S,F> as futures::stream::Stream>::poll
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.29/src/stream/map.rs:79
  23: <futures::stream::fold::Fold<S,F,Fut,T> as futures::future::Future>::poll
  24: futures::future::chain::Chain<A,B,C>::poll
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.29/src/future/chain.rs:26
  25: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.29/src/future/then.rs:32
  26: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.29/src/future/mod.rs:113
  27: futures::task_impl::NotifyHandle::new
  28: futures::task_impl::NotifyHandle::new
  29: futures::task_impl::std::BorrowedUnpark::new
  30: futures::task_impl::NotifyHandle::new
  31: futures::task_impl::NotifyHandle::new
  32: futures::task_impl::NotifyHandle::new
  33: tokio_threadpool::task::Task::run::{{closure}}
  34: core::ops::function::FnOnce::call_once
  35: <tokio_threadpool::task::state::State as core::cmp::PartialEq>::eq
  36: std::sys::unix::mutex::Mutex::destroy
  37: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  38: std::sys::unix::mutex::Mutex::destroy
  39: std::collections::hash::map::RandomState::new
  40: tokio_threadpool::task::Task::run
  41: tokio_threadpool::worker::Worker::run_task2
  42: tokio_threadpool::worker::Worker::run_task
  43: tokio_threadpool::worker::Worker::try_run_owned_task
  44: tokio_threadpool::worker::Worker::try_run_task
  45: tokio_threadpool::worker::Worker::with_current::{{closure}}
  46: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.22/src/runtime/threadpool/builder.rs:390
  47: tokio_timer::timer::handle::with_default
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-timer-0.2.13/src/timer/handle.rs:74
  48: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.22/src/runtime/threadpool/builder.rs:382
  49: tokio_timer::clock::clock::with_default
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-timer-0.2.13/src/clock/clock.rs:125
  50: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.22/src/runtime/threadpool/builder.rs:381
  51: tokio_reactor::with_default
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-reactor-0.1.12/src/lib.rs:220
  52: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /Users/yihuang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.22/src/runtime/threadpool/builder.rs:380
  53: tokio_threadpool::callback::Callback::call
  54: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
  55: <tokio_threadpool::task::state::State as core::cmp::PartialEq>::eq
  56: crossbeam_epoch::internal::Local::is_pinned
  57: crossbeam_epoch::internal::Local::is_pinned
  58: <tokio_threadpool::task::state::State as core::cmp::PartialEq>::eq
  59: tokio_threadpool::worker::Worker::do_run::{{closure}}
  60: crossbeam_epoch::internal::Local::is_pinned
  61: crossbeam_epoch::internal::Local::is_pinned
  62: tokio_threadpool::worker::Worker::do_run
  63: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
  64: std::sys_common::poison::Flag::borrow
  65: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/thread/mod.rs:469
  66: <tokio_threadpool::task::state::State as core::cmp::PartialEq>::eq
  67: std::sys::unix::mutex::Mutex::destroy
  68: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  69: std::sys::unix::mutex::Mutex::destroy
  70: std::collections::hash::map::RandomState::new
  71: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/thread/mod.rs:468
  72: core::ops::function::FnOnce::call_once{{vtable.shim}}
  73: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  74: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  75: std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
  76: std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  77: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`/consensus/timeout_commit` is set to `10s`, so block generation is slow, triggered some race conditions.

**Comment by tomtau** [comment]
@yihuang can you reproduce with DEBUG log level?

**Comment by tomtau** [comment]
@yihuang seems this can happen -- validator leaves (valid) and later there's a byzantine evidence?

**Comment by yihuang** [comment]
> @yihuang seems this can happen -- validator leaves (valid) and later there's a byzantine evidence?

The validator's metadata is cleaned up, then appears in `last_commit_info`, this can happen if `block generation time > cleanup scheduled time`.

**Comment by tomtau** [comment]
probably no longer relevant, as the revised staking design is implemented
