### ISSUE TITLE
Problem: newer version of aes-gcm-siv fails tests

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1200]
```
test wallet::syncer_logic::tests::check_syncer_logic_basic ... FAILED
1279test wallet::syncer_logic::tests::check_syncer_logic_tx_flow ... FAILED
1280test wallet::syncer::tests::check_wallet_syncer_app_hash_on_multiple_tx ... ok
1281
1282failures:
1283
1284---- service::hd_key_service::tests::check_deterministic_hdkey_transfer stdout ----
1285thread 'service::hd_key_service::tests::check_deterministic_hdkey_transfer' panicked at 'assertion failed: n_blocks < B::ParBlocks::to_usize()', <::core::macros::panic macros>:3:10
1286stack backtrace:
1287   0: backtrace::backtrace::libunwind::trace
1288             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
1289   1: backtrace::backtrace::trace_unsynchronized
1290             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
1291   2: std::sys_common::backtrace::_print_fmt
1292             at src/libstd/sys_common/backtrace.rs:84
1293   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1294             at src/libstd/sys_common/backtrace.rs:61
1295   4: core::fmt::write
1296             at src/libcore/fmt/mod.rs:1025
1297   5: std::io::Write::write_fmt
1298             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/io/mod.rs:1426
1299   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
1300             at src/libstd/io/impls.rs:156
1301   7: std::sys_common::backtrace::_print
1302             at src/libstd/sys_common/backtrace.rs:65
1303   8: std::sys_common::backtrace::print
1304             at src/libstd/sys_common/backtrace.rs:50
1305   9: std::panicking::default_hook::{{closure}}
1306             at src/libstd/panicking.rs:193
1307  10: std::panicking::default_hook
1308             at src/libstd/panicking.rs:207
1309  11: std::panicking::rust_panic_with_hook
1310             at src/libstd/panicking.rs:471
1311  12: rust_begin_unwind
1312             at src/libstd/panicking.rs:375
1313  13: core::panicking::panic_fmt
1314             at src/libcore/panicking.rs:84
1315  14: core::panicking::panic
1316             at src/libcore/panicking.rs:51
1317  15: aes_gcm_siv::ctr::Ctr32<B>::apply_keystream_blocks
1318             at /home/travis/build/crypto-com/chain/<::core::macros::panic macros>:2
1319  16: aes_gcm_siv::ctr::Ctr32<B>::apply_keystream
1320             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/aes-gcm-siv-0.4.0/src/ctr.rs:52
1321  17: aes_gcm_siv::Cipher<B>::encrypt_in_place_detached
1322             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/aes-gcm-siv-0.4.0/src/lib.rs:313
1323  18: <aes_gcm_siv::AesGcmSiv<B> as aead::Aead>::encrypt_in_place_detached
1324             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/aes-gcm-siv-0.4.0/src/lib.rs:211
1325  19: aead::Aead::encrypt_in_place
1326             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/aead-0.2.0/src/lib.rs:123
1327  20: aead::Aead::encrypt
1328             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/aead-0.2.0/src/lib.rs:104
1329  21: client_common::storage::encrypt_bytes
1330             at /home/travis/build/crypto-com/chain/client-common/src/storage.rs:227
1331  22: <T as client_common::storage::SecureStorage>::fetch_and_update_secure::{{closure}}::{{closure}}
1332             at /home/travis/build/crypto-com/chain/client-common/src/storage.rs:204
1333  23: core::option::Option<T>::map
1334             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/option.rs:450
1335  24: <T as client_common::storage::SecureStorage>::fetch_and_update_secure::{{closure}}
1336             at /home/travis/build/crypto-com/chain/client-common/src/storage.rs:203
1337  25: <client_common::storage::memory_storage::MemoryStorage as client_common::storage::Storage>::fetch_and_update
1338             at /home/travis/build/crypto-com/chain/client-common/src/storage/memory_storage.rs:102
1339  26: <T as client_common::storage::SecureStorage>::fetch_and_update_secure
1340             at /home/travis/build/crypto-com/chain/client-common/src/storage.rs:190
1341  27: client_core::service::wallet_service::WalletService<T>::modify_wallet
1342             at client-core/src/service/wallet_service.rs:398
1343  28: client_core::service::wallet_service::WalletService<T>::add_public_key
1344             at client-core/src/service/wallet_service.rs:377
1345  29: <client_core::wallet::default_wallet_client::DefaultWalletClient<S,C,T> as client_core::wallet::WalletClient>::new_transfer_address
1346             at client-core/src/wallet/default_wallet_client.rs:524
1347  30: client_core::service::hd_key_service::tests::check_deterministic_hdkey_transfer
1348             at client-core/src/service/hd_key_service.rs:288
1349  31: client_core::service::hd_key_service::tests::check_deterministic_hdkey_transfer::{{closure}}
1350             at client-core/src/service/hd_key_service.rs:267
1351  32: core::ops::function::FnOnce::call_once
1352             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ops/function.rs:232
1353  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
1354             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1022
1355  34: __rust_maybe_catch_panic
1356             at src/libpanic_unwind/lib.rs:78
1357  35: std::panicking::try
1358             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panicking.rs:270
1359  36: std::panic::catch_unwind
1360             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panic.rs:394
1361  37: test::run_test_in_process
1362             at src/libtest/lib.rs:567
1363  38: test::run_test::run_test_inner::{{closure}}
1364             at src/libtest/lib.rs:474
1365note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tomtau** [comment]
https://travis-ci.org/crypto-com/chain/jobs/659623002
https://github.com/crypto-com/chain/pull/1197

**Comment by tomtau** [comment]
fixed in https://github.com/crypto-com/chain/pull/1201
