### ISSUE TITLE
Problem: cargo kcov occasionally crashing on `test_dev_config_file`

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1585]
e.g. https://travis-ci.org/github/crypto-com/chain/jobs/685477717#L1617
```
failures:
1616
1617---- commands::genesis_command::test::test_dev_config_file stdout ----
1618thread 'commands::genesis_command::test::test_dev_config_file' panicked at 'can not find example-dev-config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', dev-utils/src/commands/genesis_command.rs:347:13
1619stack backtrace:
1620   0: backtrace::backtrace::libunwind::trace
1621             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1622   1: backtrace::backtrace::trace_unsynchronized
1623             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
1624   2: std::sys_common::backtrace::_print_fmt
1625             at src/libstd/sys_common/backtrace.rs:78
1626   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1627             at src/libstd/sys_common/backtrace.rs:59
1628   4: core::fmt::write
1629             at src/libcore/fmt/mod.rs:1069
1630   5: std::io::Write::write_fmt
1631             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/io/mod.rs:1537
1632   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
1633             at src/libstd/io/impls.rs:176
1634   7: std::sys_common::backtrace::_print
1635             at src/libstd/sys_common/backtrace.rs:62
1636   8: std::sys_common::backtrace::print
1637             at src/libstd/sys_common/backtrace.rs:49
1638   9: std::panicking::default_hook::{{closure}}
1639             at src/libstd/panicking.rs:198
1640  10: std::panicking::default_hook
1641             at src/libstd/panicking.rs:215
1642  11: std::panicking::rust_panic_with_hook
1643             at src/libstd/panicking.rs:477
1644  12: rust_begin_unwind
1645             at src/libstd/panicking.rs:385
1646  13: core::panicking::panic_fmt
1647             at src/libcore/panicking.rs:89
1648  14: core::option::expect_none_failed
1649             at src/libcore/option.rs:1272
1650  15: core::result::Result<T,E>::expect
1651             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libcore/result.rs:963
1652  16: dev_utils::commands::genesis_command::test::test_dev_config_file
1653             at dev-utils/src/commands/genesis_command.rs:347
1654  17: dev_utils::commands::genesis_command::test::test_dev_config_file::{{closure}}
1655             at dev-utils/src/commands/genesis_command.rs:344
1656  18: core::ops::function::FnOnce::call_once
1657             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libcore/ops/function.rs:232
1658  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
1659             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/liballoc/boxed.rs:1034
1660  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
1661             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/panic.rs:318
1662  21: std::panicking::try::do_call
1663             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/panicking.rs:297
1664  22: std::panicking::try
1665             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/panicking.rs:274
1666  23: std::panic::catch_unwind
1667             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/panic.rs:394
1668  24: test::run_test_in_process
1669             at src/libtest/lib.rs:541
1670  25: test::run_test::run_test_inner::{{closure}}
1671             at src/libtest/lib.rs:450
1672note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tomtau** [comment]
maybe can be fixed using `include_str!` macro to read the file at compile time instead of runtime?
