### ISSUE TITLE
Problem: non-reproducible Python dependencies in integration tests

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1934]
https://github.com/crypto-com/chain/pull/1928#issuecomment-657306646
```
Preparing... WITH_FEE
146	Traceback (most recent call last):
147	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 582, in _build_master
148	    ws.require(__requires__)
149	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 899, in require
150	    needed = self.resolve(parse_requirements(requirements))
151	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 790, in resolve
152	    raise VersionConflict(dist, req).with_context(dependent_req)
153	pkg_resources.ContextualVersionConflict: (base58 2.0.1 (/drone/src/drone/venv/lib/python3.8/site-packages), Requirement.parse('base58==1.0.3'), {'scalecodec'})
154	
155	During handling of the above exception, another exception occurred:
156	
157	Traceback (most recent call last):
158	  File "/drone/src/drone/venv/bin/chainbot.py", line 4, in <module>
159	    __import__('pkg_resources').require('crypto-chain-bot==1.0')
160	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3257, in <module>
161	    def _initialize_master_working_set():
162	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
163	    f(*args, **kwargs)
164	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
165	    working_set = WorkingSet._build_master()
166	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
167	    return cls._build_from_requirements(__requires__)
168	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 597, in _build_from_requirements
169	    dists = ws.resolve(reqs, Environment())
170	  File "/drone/src/drone/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 790, in resolve
171	    raise VersionConflict(dist, req).with_context(dependent_req)
172	pkg_resources.ContextualVersionConflict: (base58 2.0.1 (/drone/src/drone/venv/lib/python3.8/site-packages), Requirement.parse('base58==1.0.3'), {'scalecodec'})
```

**Comment by leejw51crypto** [comment]
started

**Comment by yihuang** [comment]
This issue seems not fixed? I'm still seeing this ;(

**Comment by yihuang** [comment]
> This issue seems not fixed? I'm still seeing this ;(

running manually is fixed in https://github.com/crypto-com/chain/pull/1944
