### ISSUE TITLE
Problem: multinode integration test unstable

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#2116]
## reward test unstable

Test log:
```
Preparing... reward
343	Prepared succesfully ./data 26650 SGX
344	genesis fingerprint: 36F6A6AF46739299085BE53B62FBC2B2A945498DDF4137CDCFAFD9BCD717AD98
345	Startup...
346	Wait for tcp port 26657
347	[Wed Aug 12 11:16:22 UTC 2020] Tcp port 26657 not available yet, sleep 2 seconds and retry
348	2020-08-12 11:16:22,645 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
349	2020-08-12 11:16:22,647 INFO RPC interface 'supervisor' initialized
350	2020-08-12 11:16:22,648 CRIT Server 'unix_http_server' running without any HTTP authentication checking
351	2020-08-12 11:16:22,648 INFO supervisord started with pid 2239
352	2020-08-12 11:16:23,650 INFO spawned: 'mock_hardware_key_storage' with pid 2245
353	2020-08-12 11:16:23,651 INFO spawned: 'chain-abci-node0' with pid 2246
354	2020-08-12 11:16:23,652 INFO spawned: 'tendermint-node0' with pid 2247
355	2020-08-12 11:16:23,654 INFO spawned: 'chain-abci-node1' with pid 2248
356	2020-08-12 11:16:23,655 INFO spawned: 'tendermint-node1' with pid 2249
357	2020-08-12 11:16:23,657 INFO spawned: 'chain-abci-node2' with pid 2250
358	2020-08-12 11:16:23,658 INFO spawned: 'tendermint-node2' with pid 2251
359	[Wed Aug 12 11:16:24 UTC 2020] Tcp port 26657 not available yet, sleep 2 seconds and retry
360	[Wed Aug 12 11:16:26 UTC 2020] Tcp port 26657 not available yet, sleep 2 seconds and retry
361	2020-08-12 11:16:26,769 INFO success: mock_hardware_key_storage entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
362	2020-08-12 11:16:26,769 INFO success: chain-abci-node0 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
363	2020-08-12 11:16:26,769 INFO success: tendermint-node0 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
364	2020-08-12 11:16:26,769 INFO success: chain-abci-node1 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
365	2020-08-12 11:16:26,769 INFO success: tendermint-node1 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
366	2020-08-12 11:16:26,769 INFO success: chain-abci-node2 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
367	2020-08-12 11:16:26,769 INFO success: tendermint-node2 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
368	Tcp port 26657 is available now
369	2020-08-12 11:16:38,448 INFO waiting for tendermint-node1 to stop
370	2020-08-12 11:16:38,458 INFO stopped: tendermint-node1 (exit status 0)
371	2020-08-12 11:16:38,459 INFO waiting for chain-abci-node1 to stop
372	2020-08-12 11:16:38,996 INFO stopped: chain-abci-node1 (terminated by SIGTERM)
373	block_time: 1597230998.990722
374	Traceback (most recent call last):
375	  File "./multinode/reward_test.py", line 80, in <module>
376	    assert int(state['bonded']) == bonded_rewarded + minted + slashed
377	AssertionError
```

```
==> data/logs/chain-abci-node0.log <==
379	[2020-08-12T11:16:23Z WARN  chain_abci] enclave_server is deprecated
380	[2020-08-12T11:16:23Z INFO  chain_abci] network=Devnet network_id=AB
381	[2020-08-12T11:16:26Z WARN  chain_abci] Enabled sanity checks
382	[2020-08-12T11:16:26Z INFO  chain_abci::enclave_bridge::edp] starting tx validation enclave
383	[INFO  tx_validation_next::sgx_module] Network ID: ab
384	[INFO  tx_validation_next::sgx_module] Connecting to chain-abci
385	[DEBUG tx_validation_next::sgx_module] waiting for chain-abci requests
386	[2020-08-12T11:16:26Z INFO  chain_abci::enclave_bridge::edp] starting tx-query data handling server
387	[2020-08-12T11:16:26Z INFO  chain_abci::enclave_bridge::edp] starting tx-query
388	[2020-08-12T11:16:26Z INFO  chain_abci::enclave_bridge::edp::server] running zmq server
389	[2020-08-12T11:16:26Z INFO  chain_abci] starting up
390	[2020-08-12T11:16:26Z INFO  chain_abci::app::app_init] no last app state stored
391	[2020-08-12T11:16:26Z INFO  chain_abci::app::app_init] enclave connection OK
392	[2020-08-12T11:16:26Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26658), peer: V4(127.0.0.1:43766), fd: 48 }
393	[2020-08-12T11:16:26Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26658), peer: V4(127.0.0.1:43772), fd: 49 }
394	[2020-08-12T11:16:26Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26658), peer: V4(127.0.0.1:43774), fd: 50 }
395	[2020-08-12T11:16:26Z INFO  chain_abci::app] received info request
396	[2020-08-12T11:16:26Z INFO  chain_abci::app] received initchain request
397	[2020-08-12T11:16:26Z WARN  chain_abci::app::app_init] consensus parameters not checked (TODO)
398	[INFO  tx_query2_enclave_app::sgx_module] Connecting to chain-abci data
399	[INFO  tx_query2_enclave_app::sgx_module] Successfully created remote attestation certificate!
400	[INFO  tx_query2_enclave_app::sgx_module] Starting TLS Server
401	[2020-08-12T11:16:28Z INFO  chain_abci::app] received beginblock request
402	[2020-08-12T11:16:28Z INFO  chain_abci::app] received endblock request
403	[2020-08-12T11:16:28Z INFO  chain_abci::app] received commit request
404	[2020-08-12T11:16:29Z INFO  chain_abci::app] received beginblock request
405	[2020-08-12T11:16:29Z INFO  chain_abci::app::rewards] minted for rewards: 69.78080000 1800000000.00000000
406	[2020-08-12T11:16:29Z INFO  chain_abci::app] received endblock request
407	[2020-08-12T11:16:29Z INFO  chain_abci::app] received commit request
408	[2020-08-12T11:16:30Z INFO  chain_abci::app] received query request
409	[2020-08-12T11:16:30Z INFO  chain_abci::app] received query request
410	[2020-08-12T11:16:31Z INFO  chain_abci::app] received beginblock request
411	[2020-08-12T11:16:31Z INFO  chain_abci::app] received endblock request
412	[2020-08-12T11:16:31Z INFO  chain_abci::app] received commit request
413	[2020-08-12T11:16:32Z INFO  chain_abci::app] received beginblock request
414	[2020-08-12T11:16:32Z INFO  chain_abci::app] received endblock request
415	[2020-08-12T11:16:32Z INFO  chain_abci::app] received commit request
416	[2020-08-12T11:16:33Z INFO  chain_abci::app] received beginblock request
417	[2020-08-12T11:16:33Z INFO  chain_abci::app] received endblock request
418	[2020-08-12T11:16:33Z INFO  chain_abci::app] received commit request
419	[2020-08-12T11:16:35Z INFO  chain_abci::app] received beginblock request
420	[2020-08-12T11:16:35Z INFO  chain_abci::app] received endblock request
421	[2020-08-12T11:16:35Z INFO  chain_abci::app] received commit request
422	[2020-08-12T11:16:36Z INFO  chain_abci::app] received beginblock request
423	[2020-08-12T11:16:36Z INFO  chain_abci::staking::table] slashing 1 stakings
424	[2020-08-12T11:16:36Z INFO  chain_abci::app] received endblock request
425	[2020-08-12T11:16:36Z INFO  chain_abci::app] received commit request
426	[2020-08-12T11:16:37Z INFO  chain_abci::app] received beginblock request
427	[2020-08-12T11:16:38Z INFO  chain_abci::app] received endblock request
428	[2020-08-12T11:16:38Z INFO  chain_abci::app] received commit request
429	[2020-08-12T11:16:38Z INFO  chain_abci::app] received query request
430	[2020-08-12T11:16:38Z INFO  chain_abci::app] received beginblock request
431	[2020-08-12T11:16:39Z INFO  chain_abci::app] received endblock request
432	[2020-08-12T11:16:39Z INFO  chain_abci::app] received commit request
433	[2020-08-12T11:16:40Z INFO  chain_abci::app] received beginblock request
434	[2020-08-12T11:16:40Z INFO  chain_abci::app::rewards] minted for rewards: 61.82420000 900000034.89040000
435	[2020-08-12T11:16:40Z INFO  chain_abci::app] received query request
436	[2020-08-12T11:16:40Z INFO  chain_abci::app] received endblock request
437	[2020-08-12T11:16:40Z INFO  chain_abci::app] received query request
438	[2020-08-12T11:16:40Z INFO  chain_abci::app] received commit request
```

client wait for a second reward distribution, by waiting for recent block time(in `sync_info` field of `status` endpoint) passes the reward distribution period, but abci log shows the second reward distribution not happen yet.

**possible reason**: abci don't processed the block yet, in spit of the `status` endpoint of tendermint already reported the block.

## join test unstable

Test log:
```
Tcp port 26657 is available now
159	Wait for 3 validators online
160	Checking validators 3
161	Stop node2
162	2020-08-12 07:38:23,337 INFO waiting for tendermint-node2 to stop
163	2020-08-12 07:38:23,346 INFO stopped: tendermint-node2 (exit status 0)
164	2020-08-12 07:38:23,350 INFO waiting for chain-abci-node2 to stop
165	2020-08-12 07:38:24,376 INFO stopped: chain-abci-node2 (terminated by SIGTERM)
166	Waiting for 8 blocks
167	punishment {'amount': '9000000000000000', 'kind': 'NonLive', 'time': 1597217909}
168	slash amount 9000000000000000
169	Starting node2
170	2020-08-12 07:38:41,651 INFO spawned: 'chain-abci-node2' with pid 471
171	2020-08-12 07:38:41,653 INFO spawned: 'tendermint-node2' with pid 472
172	2020-08-12 07:38:41,655 INFO spawned: 'client-rpc-node2' with pid 473
173	2020-08-12 07:38:41,949 INFO exited: client-rpc-node2 (exit status 101; not expected)
174	2020-08-12 07:38:43,212 INFO spawned: 'client-rpc-node2' with pid 499
175	2020-08-12 07:38:43,489 INFO exited: client-rpc-node2 (exit status 101; not expected)
176	2020-08-12 07:38:44,710 INFO success: chain-abci-node2 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
177	2020-08-12 07:38:44,711 INFO success: tendermint-node2 entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
178	Traceback (most recent call last):
179	  File "./multinode/join_test.py", line 70, in <module>
180	Started node2
181	    jailed_until = state['node_meta']['CouncilNode']['jailed_until']
182	TypeError: 'NoneType' object is not subscriptable
```

```

==> data/logs/chain-abci-node0.log <==
--
184
...
[2020-08-12T07:38:20Z INFO  chain_abci::app] received beginblock request
207	[2020-08-12T07:38:20Z INFO  chain_abci::app] received endblock request
208	[2020-08-12T07:38:20Z INFO  chain_abci::app] received commit request
209	[2020-08-12T07:38:21Z INFO  chain_abci::app] received beginblock request
210	[2020-08-12T07:38:22Z INFO  chain_abci::app] received endblock request
211	[2020-08-12T07:38:22Z INFO  chain_abci::app] received commit request
212	[2020-08-12T07:38:27Z INFO  chain_abci::app] received beginblock request
213	[2020-08-12T07:38:27Z INFO  chain_abci::app] received endblock request
214	[2020-08-12T07:38:27Z INFO  chain_abci::app] received commit request
215	[2020-08-12T07:38:28Z INFO  chain_abci::app] received beginblock request
216	[2020-08-12T07:38:28Z INFO  chain_abci::app] received endblock request
217	[2020-08-12T07:38:28Z INFO  chain_abci::app] received commit request
218	[2020-08-12T07:38:30Z INFO  chain_abci::app] received beginblock request
219	[2020-08-12T07:38:30Z INFO  chain_abci::app] received endblock request
220	[2020-08-12T07:38:30Z INFO  chain_abci::app] received commit request
221	[2020-08-12T07:38:35Z INFO  chain_abci::app] received beginblock request
222	[2020-08-12T07:38:35Z INFO  chain_abci::staking::table] slashing 1 stakings
223	[2020-08-12T07:38:35Z INFO  chain_abci::app] received endblock request
224	[2020-08-12T07:38:35Z INFO  chain_abci::app] received commit request
225	[2020-08-12T07:38:36Z INFO  chain_abci::app] received beginblock request
226	[2020-08-12T07:38:37Z INFO  chain_abci::app] received endblock request
227	[2020-08-12T07:38:37Z INFO  chain_abci::app] received commit request
228	[2020-08-12T07:38:38Z INFO  chain_abci::app] received beginblock request
229	[2020-08-12T07:38:38Z INFO  chain_abci::app] received endblock request
230	[2020-08-12T07:38:38Z INFO  chain_abci::app] received commit request
231	[2020-08-12T07:38:39Z INFO  chain_abci::app] received beginblock request
232	[2020-08-12T07:38:39Z INFO  chain_abci::app] received endblock request
233	[2020-08-12T07:38:39Z INFO  chain_abci::app] received commit request
234	[2020-08-12T07:38:41Z INFO  chain_abci::app] received beginblock request
235	[2020-08-12T07:38:41Z INFO  chain_abci::staking::table] cleanup validators: 1
236	[2020-08-12T07:38:41Z INFO  chain_abci::app] received endblock request
237	[2020-08-12T07:38:41Z INFO  chain_abci::app] received commit request
238	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
239	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
240	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
241	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
242	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
243	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
244	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
245	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
246	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
247	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
248	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
249	[2020-08-12T07:38:41Z INFO  chain_abci::app] received query request
250	[2020-08-12T07:38:42Z INFO  chain_abci::app] received beginblock request
251	[2020-08-12T07:38:42Z INFO  chain_abci::app] received endblock request
252	[2020-08-12T07:38:42Z INFO  chain_abci::app] received commit request
253	[2020-08-12T07:38:43Z INFO  chain_abci::app] received beginblock request
254	[2020-08-12T07:38:44Z INFO  chain_abci::app] received endblock request
255	[2020-08-12T07:38:44Z INFO  chain_abci::app] received commit request
```

```
==> data/logs/chain-abci-node1.log <==
[2020-08-12T07:38:20Z INFO  chain_abci::app] received beginblock request
281	[2020-08-12T07:38:20Z INFO  chain_abci::app] received endblock request
282	[2020-08-12T07:38:20Z INFO  chain_abci::app] received commit request
283	[2020-08-12T07:38:22Z INFO  chain_abci::app] received beginblock request
284	[2020-08-12T07:38:22Z INFO  chain_abci::app] received endblock request
285	[2020-08-12T07:38:22Z INFO  chain_abci::app] received commit request
286	[2020-08-12T07:38:27Z INFO  chain_abci::app] received beginblock request
287	[2020-08-12T07:38:27Z INFO  chain_abci::app] received endblock request
288	[2020-08-12T07:38:27Z INFO  chain_abci::app] received commit request
289	[2020-08-12T07:38:28Z INFO  chain_abci::app] received beginblock request
290	[2020-08-12T07:38:28Z INFO  chain_abci::app] received endblock request
291	[2020-08-12T07:38:28Z INFO  chain_abci::app] received commit request
292	[2020-08-12T07:38:30Z INFO  chain_abci::app] received beginblock request
293	[2020-08-12T07:38:30Z INFO  chain_abci::app] received endblock request
294	[2020-08-12T07:38:30Z INFO  chain_abci::app] received commit request
295	[2020-08-12T07:38:35Z INFO  chain_abci::app] received beginblock request
296	[2020-08-12T07:38:35Z INFO  chain_abci::staking::table] slashing 1 stakings
297	[2020-08-12T07:38:35Z INFO  chain_abci::app] received endblock request
298	[2020-08-12T07:38:35Z INFO  chain_abci::app] received commit request
299	[2020-08-12T07:38:36Z INFO  chain_abci::app] received beginblock request
300	[2020-08-12T07:38:36Z INFO  chain_abci::app] received endblock request
301	[2020-08-12T07:38:36Z INFO  chain_abci::app] received commit request
302	[2020-08-12T07:38:38Z INFO  chain_abci::app] received beginblock request
303	[2020-08-12T07:38:38Z INFO  chain_abci::app] received endblock request
304	[2020-08-12T07:38:38Z INFO  chain_abci::app] received commit request
305	[2020-08-12T07:38:39Z INFO  chain_abci::app] received beginblock request
306	[2020-08-12T07:38:39Z INFO  chain_abci::app] received endblock request
307	[2020-08-12T07:38:39Z INFO  chain_abci::app] received commit request
308	[2020-08-12T07:38:40Z INFO  chain_abci::app] received beginblock request
309	[2020-08-12T07:38:40Z INFO  chain_abci::staking::table] cleanup validators: 1
310	[2020-08-12T07:38:40Z INFO  chain_abci::app] received endblock request
311	[2020-08-12T07:38:41Z INFO  chain_abci::app] received commit request
312	[2020-08-12T07:38:42Z INFO  chain_abci::app] received beginblock request
313	[2020-08-12T07:38:42Z INFO  chain_abci::app] received endblock request
314	[2020-08-12T07:38:42Z INFO  chain_abci::app] received commit request
315	[2020-08-12T07:38:43Z INFO  chain_abci::app] received beginblock request
316	[2020-08-12T07:38:43Z INFO  chain_abci::app] received endblock request
317	[2020-08-12T07:38:43Z INFO  chain_abci::app] received commit request

```

```

==> data/logs/chain-abci-node2.log <==

[2020-08-12T07:38:19Z INFO  chain_abci] starting up
330	[2020-08-12T07:38:19Z INFO  chain_abci::app::app_init] no last app state stored
331	[2020-08-12T07:38:19Z INFO  chain_abci::app::app_init] enclave connection OK
332	[2020-08-12T07:38:19Z INFO  chain_abci::enclave_bridge::edp] starting tx-query
333	[INFO  tx_query2_enclave_app::sgx_module] Connecting to chain-abci data
334	[INFO  tx_query2_enclave_app::sgx_module] Successfully created remote attestation certificate!
335	[INFO  tx_query2_enclave_app::sgx_module] Starting TLS Server
336	[2020-08-12T07:38:22Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:36390), fd: 53 }
337	[2020-08-12T07:38:22Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:36392), fd: 54 }
338	[2020-08-12T07:38:22Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:36394), fd: 55 }
339	[2020-08-12T07:38:22Z INFO  chain_abci::app] received info request
340	[2020-08-12T07:38:22Z INFO  chain_abci::app] received initchain request
341	[2020-08-12T07:38:22Z WARN  chain_abci::app::app_init] consensus parameters not checked (TODO)
342	[2020-08-12T07:38:22Z INFO  chain_abci::app] received beginblock request
343	[2020-08-12T07:38:22Z INFO  chain_abci::app] received endblock request
344	[2020-08-12T07:38:22Z INFO  chain_abci::app] received commit request
345	[2020-08-12T07:38:41Z WARN  chain_abci] enclave_server is deprecated
346	[2020-08-12T07:38:41Z INFO  chain_abci] network=Devnet network_id=AB
347	[2020-08-12T07:38:43Z WARN  chain_abci] Enabled sanity checks
348	[2020-08-12T07:38:43Z INFO  chain_abci::enclave_bridge::edp] starting tx validation enclave
349	[INFO  tx_validation_next::sgx_module] Network ID: ab
350	[INFO  tx_validation_next::sgx_module] Connecting to chain-abci
351	[DEBUG tx_validation_next::sgx_module] waiting for chain-abci requests
352	[2020-08-12T07:38:43Z INFO  chain_abci::enclave_bridge::edp] starting tx-query data handling server
353	[2020-08-12T07:38:43Z INFO  chain_abci::enclave_bridge::edp] starting tx-query
354	[2020-08-12T07:38:43Z INFO  chain_abci::enclave_bridge::edp::server] running zmq server
355	[2020-08-12T07:38:43Z INFO  chain_abci] starting up
356	[2020-08-12T07:38:43Z INFO  chain_abci::app::app_init] last app state stored
357	[2020-08-12T07:38:43Z INFO  chain_abci::app::app_init] historical data is stored
358	[2020-08-12T07:38:43Z INFO  chain_abci::app::app_init] enclave connection OK
359	[INFO  tx_query2_enclave_app::sgx_module] Connecting to chain-abci data
360	[INFO  tx_query2_enclave_app::sgx_module] Successfully created remote attestation certificate!
361	[INFO  tx_query2_enclave_app::sgx_module] Starting TLS Server
362	[2020-08-12T07:38:44Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:36540), fd: 60 }
363	[2020-08-12T07:38:44Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:36542), fd: 61 }
364	[2020-08-12T07:38:44Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:36544), fd: 62 }
365	[2020-08-12T07:38:44Z INFO  chain_abci::app] received info request

```

client wait for node to be slashed for non-live fault, it waited for `MISS_BLOCK_THREHOLD` blocks, and try to fetch staking state and check the jail status, but find that the `CouncilNode` is `None`.

**possible reason**: when client fetching staking state, the node not only slashed, but get cleaned up already.

**Comment by leejw51crypto** [comment]
how often it breaks? 
i mean everytime, or after some tries?

**Comment by tomtau** [comment]
@leejw51crypto for example in this PR, it was quite frequent: https://github.com/crypto-com/chain/pull/2108
but when I tried running it with `drone exec`, it didn't happen.
For the reward issue, I think @yihuang found out the cause:
```
[2020-08-13T09:56:55Z INFO  chain_abci::app::rewards] minted for rewards: 61.82420000 900000034.89040000
[2020-08-13T09:56:55Z INFO  chain_abci::app] received endblock request
[2020-08-13T09:56:55Z INFO  chain_abci::app] received query request
[2020-08-13T09:56:55Z INFO  chain_abci::app] received query request
[2020-08-13T09:56:55Z INFO  chain_abci::app] received commit request
```

 the abci-query is done before block commit.
One way to fix it will be to do the staking abci-query using the block height reported by `status` endpoint (which ),  and retry for a while if not exist: https://github.com/crypto-com/chain/pull/2119/files
